### ISSUE TITLE
Link doesn't expose ServerBootstrap

### ISSUE THREAD

**Issue by vspinu** [sunng87/link#27]
Currently ServerBootstrap is [not exposed](https://github.com/sunng87/link/blob/master/src/link/tcp.clj#L64). I think that similarly to the client channel, users should be able to access underlying server. Would it be possible to return it as part of that vector or better, return a map like `{:boos-group .., :worker-group ..., :bootstrap ...}`?

**Comment by sunng87** [comment]
That's a design choice. The Bootstrap instance for client is exposed via `tcp-client-factory`. But for server, we create `ServerBootstrap` for each instance. 

One idea to fix is adding an option for `tcp-server` that accept existed worker-group, boss-group and bootstrap instead of creating new one.

**Comment by vspinu** [comment]
> That's a design choice. 

Why is that useful? My application might want to get id, local-address, remote-address etc. from the server just as it does with clients. 

> One idea to fix is adding an option for tcp-server

One way indeed.

**Comment by vspinu** [comment]
I am afraid I was a bit confused here. What I actually was looking for is the ServerSocketChannel. AFAICS there is no way to get it out from the bootstrap.  It can be extracted from the future:

```clj
(.channel (.sync ^ChannelFuture (.bind bootstrap (InetAddress/getByName host) port)))
```
